[package]
name = "sadmin2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
base64 = "0.13.0"
bytes = "1.2.1"
dirs = "4.0.0"
futures-util = "0.3.24"
itertools = "0.10.5"
log = "0.4.17"
rand = "0.8.5"
rpassword = "7.0.0"
serde = { version = "1.0.144", default-features = false, features=['std', 'derive']}
serde_json = { version = "1.0.85", default-features = false, features=['std'] }
tokio = { version = "1.21.1", default-features = false, features=['rt', 'net', 'fs', 'sync', 'macros', 'time', 'process'] }
tokio-rustls = "0.23.4"
tokio-tungstenite = { version = "0.17.2", features=['rustls-tls-webpki-roots']}
webpki = "0.22.0"
webpki-roots = "0.22.5"
simple_logger = {version = "2", default-features=false }
tempfile = "3.3.0"
clap = {version = "4.0.9", default-features = false, features=['std', 'derive', 'help', 'suggestions']}
sdnotify = {version = "0.2.0", default-features = false}
reqwest = {version = "0.11.12",  default-features = false, features=['json', 'rustls-tls-webpki-roots']}
zip = {version= "0.6.3",  default-features = false, features=['deflate']}
indicatif = "0.17.1"
