[package]
name = "sadmin2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21.0"
bytes = "1"
dirs = "5"
futures-util = "0.3"
itertools = "0.10"
log = "0.4"
rand = "0.8"
rpassword = "7"
serde = { version = "1", default-features = false, features=['std', 'derive']}
serde_json = { version = "1", default-features = false, features=['std'] }
tokio = { version = "1", default-features = false, features=['rt', 'net', 'fs', 'sync', 'macros', 'time', 'process', 'signal'] }
tokio-rustls = "0.24"
tokio-tungstenite = { version = "0.18", features=['rustls-tls-webpki-roots']}
webpki = "0.22"
webpki-roots = "0.23"
simple_logger = {version = "4", default-features=false }
tempfile = "3"
clap = {version = "4", default-features = false, features=['std', 'derive', 'help', 'suggestions', 'usage', 'color']}
sdnotify = {version = "0.2", default-features = false}
reqwest = {version = "0.11",  default-features = false, features=['json', 'rustls-tls-webpki-roots']}
zip = {version= "0.6",  default-features = false, features=['deflate']}
indicatif = "0.17"
nix = { version = "0.26", default-features = false, features = ["signal", "user", "fs", "event", "socket", "uio"] }
rusqlite = { version = "0.29", features = ["bundled"] }
serde_yaml = "0.9"
cgroups-rs = "0.2"
passfd = "0.1"
tokio-tasks = "0.1"
chrono = {version = "0.4", default-features = false, features = ["std", "clock"] }
hyper = { version = "0.14", features = ["server", "http1"] }

