[package]
name = "sadmin2"
version = "0.1.0"
edition = "2021"

[features]
daemon = [
    "tokio-rustls",
    "log",
    "sdnotify",
    "nix",
    "tokio-tasks",
    "chrono",
    "cgroups-rs",
    "passfd",
    "hyper",
    "serde_yaml",
    "tempfile",
    "rusqlite"]

[dependencies]
anyhow = "1"
base64 = "0.21.0"
bytes = "1"
dirs = "5"
futures-util = "0.3"
itertools = "0.10"
log = {version = "0.4", optional=true}
rand = "0.8"
rpassword = "7"
serde = { version = "1", default-features = false, features=['std', 'derive']}
serde_json = { version = "1", default-features = false, features=['std'] }
tokio = { version = "1", default-features = false, features=['rt', 'net', 'fs', 'sync', 'macros', 'time', 'process', 'signal'] }
tokio-rustls = {version="0.24", optional=true}
tokio-tungstenite = { version = "0.18", features=['rustls-tls-webpki-roots']}
webpki = "0.22"
webpki-roots = "0.23"
simple_logger = {version = "4", default-features=false }
tempfile = {version="3", optional=true}
clap = {version = "4", default-features = false, features=['std', 'derive', 'help', 'suggestions', 'usage', 'color']}
sdnotify = {version = "0.2", default-features = false, optional=true}
reqwest = {version = "0.11",  default-features = false, features=['json', 'rustls-tls-webpki-roots']}
zip = {version= "0.6",  default-features = false, features=['deflate']}
indicatif = "0.17"
nix = { version = "0.26", default-features = false, features = ["signal", "user", "fs", "event", "socket", "uio"], optional=true}
rusqlite = { version = "0.29", features = ["bundled"], optional=true}
serde_yaml = {version = "0.9", optional=true}
cgroups-rs = {version = "0.2", optional=true}
passfd = {version = "0.1", optional=true}
tokio-tasks = {version = "0.1", optional=true}
chrono = {version = "0.4", default-features = false, features = ["std", "clock"], optional=true}
hyper = { version = "0.14", features = ["server", "http1"], optional=true}

