[package]
name = "simple_admin_server_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
base64 = "0.22"
libc = "0.2"
neon = "1"
totp-rs= {version="5", features = ["otpauth"]}
