on: [pull_request]
name: Frontend Continuous integration
jobs:
  build:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run format:check
