on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

# Required so the release can be created/updated with the default GITHUB_TOKEN.
permissions:
  contents: write

jobs:
  linux:
    name: Upload Release Asset Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: echo "${{ github.ref_name }}" > src/version.txt
      - run: cargo build --release --features=daemon,nix
      - run: strip target/release/sadmin
      - run: zip --junk-paths sadmin-client target/release/sadmin
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: sadmin-client.zip

  osx:
    name: Upload Release Asset OSX
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - run: strip target/release/sadmin
      - run: zip --junk-paths sadmin-client-osx target/release/sadmin
      - name: Upload Release Asset OSX
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: sadmin-client-osx.zip

  win:
    name: Upload Release Asset Win
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - name: Upload Release Asset Win
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: target/release/sadmin.exe
